
platform :ios, '12.0'
use_frameworks!

target 'WZPagerView_Example' do
  pod 'WZPagerView', :path => '../'
  pod 'JXCategoryView', '~> 1.5.8'
  pod 'MJRefresh', '~> 3.2.0'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 12.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
  
end
